
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:28 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/"
      - "/home/zuzu/.local/share/omarchy/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
    searched_directories:
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/uname"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/uname"
      - "/home/zuzu/.local/share/omarchy/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux"
        - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64"
        - "/home/zuzu/.local/share/omarchy/bin/"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:28 (project)"
    message: |
      The system is: Linux - 6.17.1-arch1-1 - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:28 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/"
      - "/home/zuzu/.local/share/omarchy/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
    searched_directories:
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/ninja-build"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/ninja"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux/samu"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/ninja-build"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/ninja"
      - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64/samu"
      - "/home/zuzu/.local/share/omarchy/bin/ninja-build"
      - "/home/zuzu/.local/share/omarchy/bin/ninja"
      - "/home/zuzu/.local/share/omarchy/bin/samu"
      - "/usr/local/sbin/ninja-build"
      - "/usr/local/sbin/ninja"
      - "/usr/local/sbin/samu"
      - "/usr/local/bin/ninja-build"
      - "/usr/local/bin/ninja"
      - "/usr/local/bin/samu"
      - "/usr/bin/ninja-build"
      - "/usr/bin/ninja"
      - "/usr/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-build-cmake-1.42.2/resources/cube-cmake/linux"
        - "/home/zuzu/.vscode/extensions/stmicroelectronics.stm32cube-ide-core-1.0.3/resources/binaries/linux/x86_64"
        - "/home/zuzu/.local/share/omarchy/bin/"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
...
